---
# tasks file for jenkins-role
- name: create the deployments and services
  command:  kubectl apply -f -
  args:
      stdin: "{{ lookup('template', 'jenkins.{{ item }}.yaml.j2') }}"
  loop:
    - deployment 
    - service  
