- name: deploy CD
  hosts:   
    - 192.168.101.31
    - 192.168.101.32  
  #gather_facts: yes
  remote_user: root
  vars:
      recursion: yes
      servers:
              - { hostname: kube-worker01, ip: 192.168.101.31 }
              - { hostname: kube-worker02, ip: 192.168.101.32 }

      ansible_python_interpreter: "{{ ansible_playbook_python }}"    
  #become: yes

  tasks:

      - name: Install apache
        yum:
          name: apache2
          state: present
          update_cache: yes


      - name: install Maven
        yum:
          name: maven
          state: present
          update_cache: yes


      - name: Install git
        yum:
          name: git
          state: present
          update_cache: yes

      - name: Install Supporting Software
        yum:
          name: software-properties-common
          state: present

      - name: Install python
        yum:
          name: python3.8
          state: present

      - name: install Java
        yum:
          name: openjdk-8-jdk
          state: present
          update_cache: yes

      
      - name: install Docker
        yum:
          name: docker
          state: present
          update_cache: yes

      - name: Install docker-compose
        remote_user: root
        get_url: 
          url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'




      - name : "git clone"
        git:
          repo: https://github.com/AyedHaithem1/cd.git
          dest: /home/master01/cd/
          version: master
          force: yes
#      - name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
#        shell: cd 
#        args:
#          executable: /bin/bash
      
      - name: Define global server configuration options copy to /etc/bind/named.conf.options
        template: src=/home/master01/ansible/deploy.sh dest=/home/master01/cd/ mode=0777           
          
      - name: MVN clean package and build
        ansible.builtin.shell:
        #become: root
          #update_cache: yes  
          cmd: mvn clean package docker:build -DskipTests 
          chdir: "/home/master01/cd/demo-rest-api"
          warn: False
      - name: MVN clean package and build
        ansible.builtin.shell:
          cmd: docker-compose up -d
          chdir: "/home/master01/cd"
          warn: False


 
  handlers:
   #- name: restart apache2
   #   service: name=apache2 state=restarted




  handlers:
   #- name: restart apache2
   #   service: name=apache2 state=restarted
