---
# tasks file for nexus-role
- name: create the deployments and services
  command:  kubectl apply -f -
  args:
      stdin: "{{ lookup('template', 'sonar.{{ item }}.yaml.j2') }}"
  loop:
    - deployment
    - service



